### ISSUE TITLE
mini tutorial on how to use diff may be useful

### ISSUE THREAD

**Issue by retsyo** [c-blake/hldiff#2]
As the title says. Thanks

**Comment by c-blake** [comment]
Could you maybe elaborate on what you think is missing from https://github.com/c-blake/hldiff#installation ?

**Comment by c-blake** [comment]
Oh, I see your [Nim Forum question](https://forum.nim-lang.org/t/8755#57185) now, though that seems like it may be directed at the other diff lib.  Give me a minute.

**Comment by c-blake** [comment]
So, I took your Forum example, added two files a & b, and produced some output.  While I used the Unix `diff` program, the same thing happens if you use the `hldiffpkg/edits.nim` example program (edit: the `isMainModule` portion) which is also sort of example code/a mini tutorial for how to use the difference calculating API.
